### ISSUE TITLE
How to create calendar entries?

### ISSUE THREAD

**Issue by hansemannn** [Aerolab/rooms#7]
Hey there,

great project! We will extend it with multi-localization / i18n soon to contribute back to it. One question that we have in the meantime is how to exactly add new calendar entries from remote / via calendar invitation. We tried sending an event invite to our service account email address, but it doesn't appear on the rooms app.

Thanks in advance!

**Comment by RobertoGonzalez** [comment]
Thanks! The app assumes the service account links to a resource object in Google Apps , so that the rooms can be booked via the Room field in Google Calendar. We haven't tried any other setups.
I'm pretty sure that the resource is just another calendar with extra metadata so sending an invite to the resource _should_ work. I'd check if the code filters unconfirmed events, which seems like the most likely explanation. 
You should also take a look at the service account permissions and make sure that calendar can be accessed via API (we included a short guide in the readme). We had a ton of trouble setting that up properly when we started building the app.

Cheers!
